name: Test and Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        env:
          process.env.ALCHEMY_API_KEY: '${{ secrets.ALCHEMY_API_KEY }}'
          process.env.PRIVATE_KEY: '${{ secrets.PRIVATE_KEY }}'
      - name: Test contracts
        run: npx hardhat test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          npm install && cd frontend && npm install
          npm run build
          cd ../ && npm run deploy
          
